# fly.toml app configuration file generated for electronics-door on 2025-07-15T17:46:00+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'electronics-door'
primary_region = 'hkg'

[http_service]
  internal_port = 8580
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
